FROM jenkins

USER root

# CMD apt-get -y update
# CMD apt-get install software-properties-common
# CMD apt-add-repository -y ppa:ansible/ansible
# CMD apt-get -y update
# CMD apt-get -y install ansible

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/jenkins.sh"]