---
- hosts: local

  tasks:
  - name: get Jenkins docker image
    shell: sudo docker build -t jenkins .

  - name: start dockerise jenkins
    shell: sudo docker run -d -p 8080:8080 -v /home/ubuntu/workspace/cd-meetup/jenkins/home:/var/jenkins_home --name myjenkins jenkins